# Generated by Django 5.2 on 2025-05-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_produ', models.AutoField(db_column='idProdu', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
