# Generated by Django 5.0.6 on 2025-06-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_herramientas_name_pinturas_name_sellantes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientas',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pinturas',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellantes',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
