# Generated by Django 5.0.6 on 2025-06-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_herramientas_stock_pinturas_stock_sellantes_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=200)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambio_stock', models.IntegerField()),
                ('stock_final', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
