# Generated by Django 5.2.1 on 2025-06-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_proveedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='Suppliers',
        ),
    ]
