# Generated by Django 5.2.1 on 2025-06-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_herramientas_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmovimiento',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
