# Generated by Django 5.2.1 on 2025-06-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_herramientas_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientas',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historialmovimiento',
            name='motivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pinturas',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productoreal',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sellantes',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
