# Generated by Django 5.2.1 on 2025-06-24 23:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_herramientas_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
            },
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in a few days')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='pinturas',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in a few days')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='productoreal',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in a few days')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='sellantes',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in a few days')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterModelTable(
            name='herramientas',
            table='inventory_herramientas',
        ),
        migrations.AlterModelTable(
            name='pinturas',
            table='inventory_pinturas',
        ),
        migrations.AlterModelTable(
            name='productoreal',
            table='inventory_productoreal',
        ),
        migrations.AlterModelTable(
            name='sellantes',
            table='inventory_sellantes',
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombre', max_length=200)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in a few days')], default='AVAILABLE', max_length=10)),
                ('issues', models.CharField(default='No Issues', max_length=50)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producttype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
