# Generated by Django 5.2.1 on 2025-06-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_producttype_alter_herramientas_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Herramientas',
        ),
        migrations.DeleteModel(
            name='Pinturas',
        ),
        migrations.DeleteModel(
            name='ProductoReal',
        ),
        migrations.DeleteModel(
            name='Sellantes',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='status',
        ),
    ]
