# Generated by Django 5.2.1 on 2025-06-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_delete_herramientas_delete_pinturas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmovimiento',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
