# Generated by Django 5.2.1 on 2025-06-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_historialmovimiento_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
