# Generated by Django 5.2.1 on 2025-06-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_suppliers_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='numero',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
