# Generated by Django 5.2.1 on 2025-06-30 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_suppliers_direccion_alter_suppliers_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmovimiento',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
