# Generated by Django 5.2.1 on 2025-07-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_add_boleta_codigo'),
        ('inventory', '0017_alter_historialmovimiento_fecha'),
    ]

    operations = [
    ]
